version: '3.9'

services:
  audit-protocol:
    image: ghcr.io/powerloom/audit-protocol:latest
    expose:
      - 9000
      - 9002
      - 9030
    ports:
      - 9000:9000
      - 9002:9002
      - 9030:9030
    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      redis:
         condition: service_healthy
      rabbitmq:
         condition: service_healthy
    #  - "ipfs"
    volumes:
      - local_cache:/home/ubuntu/local_cache/
    links:
    #  - "ipfs"
      - "redis"
      - "rabbitmq"
    environment:
      - RPC_URL=$RPC_URL
      - UUID=$UUID
      - WEB3_STORAGE_TOKEN=$WEB3_STORAGE_TOKEN
      - CONSENSUS_URL=$CONSENSUS_URL
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9000/projects/updates"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command:
      bash -c "sh snapshotter_autofill.sh && sh init_processes.sh"


  pooler:
    image: ghcr.io/powerloom/pooler:latest
    depends_on:
      audit-protocol:
        condition: service_healthy
    expose:
      - 8002
    ports:
      - 8002:8002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RPC_URL=$RPC_URL
      - UUID=$UUID
      - CONSENSUS_URL=$CONSENSUS_URL
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8002/v2-pairs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command:
      bash -c "sh snapshotter_autofill.sh && sh init_processes.sh"

  pooler-frontend:
    image: ghcr.io/powerloom/pooler-frontend:latest
    depends_on:
      pooler:
        condition: service_healthy
    expose:
      - 3000
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  redis:
    command: ["redis-server"]
    image: "redis"
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  rabbitmq:
    image: rabbitmq:3-management
    #command: ["daemon"]
    expose:
      - 15672
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  #ipfs:
  #  image: ipfs/go-ipfs:release
  #  command: ["daemon", "--migrate=true", #"--enable-pubsub-experiment"]
  #  ports:
  #    - 5001:5001
volumes:
  local_cache: